## 1.ndarray的特性
### 多维性

In [2]:
import numpy

In [3]:
arr = numpy.array(3)#零维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

3的维度为： 0


In [4]:
arr = numpy.array([1,2,3])#1维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

[1 2 3]的维度为： 1


In [5]:
arr = numpy.array([[4,5,6],[1,2,3]])#1维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

[[4 5 6]
 [1 2 3]]的维度为： 2


### 同质性

In [6]:
arr = numpy.array([1,"hello"])#不同数据类型会被转换成统一的数据类型
print(f"{arr}的数据类型为：",arr.dtype)

['1' 'hello']的数据类型为： <U11


### 2.ndarray属性

In [7]:
arr = numpy.array(3)
print("数组形状为：",arr.shape)
print("数组维度为：",arr.ndim)
print("元素的个数为：",arr.size)
print("元素的数据类型：",arr.dtype)

数组形状为： ()
数组维度为： 0
元素的个数为： 1
元素的数据类型： int32


In [8]:
arr_1 = numpy.array([1,2.5,3])
print("数组形状为：",arr_1.shape)
print("数组维度为：",arr_1.ndim)
print("元素的个数为：",arr_1.size)
print("元素的数据类型：",arr_1.dtype)

数组形状为： (3,)
数组维度为： 1
元素的个数为： 3
元素的数据类型： float64


In [9]:
arr_2 = numpy.array([[1,2,3],[4,5,6]])
print("数组形状为：",arr_2.shape)
print("数组维度为：",arr_2.ndim)
print("元素的个数为：",arr_2.size)
print("元素的数据类型：",arr_2.dtype)
print("元素的转置：",arr_2.T)

数组形状为： (2, 3)
数组维度为： 2
元素的个数为： 6
元素的数据类型： int32
元素的转置： [[1 4]
 [2 5]
 [3 6]]


### 3.ndarray的创建

In [ ]:
# 预定义形状

arr_zeros = numpy.zeros((2,3),dtype=int)
print("全零二维三列数组：\n",arr_zeros)

全零二维三列数组：
 [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr_ones = numpy.ones((2,3))
print("全一二维数组：\n",arr_ones)

全一二维数组：
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr_empty = numpy.empty((3,3)) 
print("空二维数组：\n",arr_empty)

空二维数组：
 [[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
arr_pull = numpy.full((2,3),7)
print("全7二维数组：\n",arr_pull)

全7二维数组：
 [[7 7 7]
 [7 7 7]]


In [24]:
# 根据已有数组形状创建新数组
arr_empty_like = numpy.empty_like(arr_pull)
print("根据arr_pull形状创建的空数组：\n",arr_empty_like)
print("--- ----------------------------------------------")
arr_ones_like = numpy.ones_like(arr_pull)
print("根据arr_pull形状创建的全一数组：\n",arr_ones_like)
print("--- ----------------------------------------------")
arr_zeros_like = numpy.zeros_like(arr_pull)
print("根据arr_pull形状创建的全零数组：\n",arr_zeros_like)
print("--- ----------------------------------------------")
arr_full_like = numpy.full_like(arr_pull,9)
print("根据arr_pull形状创建的全9数组：\n",arr_full_like)

根据arr_pull形状创建的空数组：
 [[          0           0  1164078128]
 [        567           0 -2147483648]]
--- ----------------------------------------------
根据arr_pull形状创建的全一数组：
 [[1 1 1]
 [1 1 1]]
--- ----------------------------------------------
根据arr_pull形状创建的全零数组：
 [[0 0 0]
 [0 0 0]]
--- ----------------------------------------------
根据arr_pull形状创建的全9数组：
 [[9 9 9]
 [9 9 9]]


In [25]:
#
arr_a = numpy.arange(1,10,2)
print("arange创建的数组：\n",arr_a)


arange创建的数组：
 [1 3 5 7 9]


In [36]:
#等间隔数列
arr_b = numpy.linspace(0,100,5)
print("linspace创建的数组：\n",arr_b)
print("--- ----------------------------------------------")
arr_b_arange = numpy.arange(0,101,25)
print("arange创建的等间隔数组：\n",arr_b_arange)

linspace创建的数组：
 [  0.  25.  50.  75. 100.]
--- ----------------------------------------------
arange创建的等间隔数组：
 [  0  25  50  75 100]


In [35]:
#对数等差数列
arr_c = numpy.logspace(0,3,2,base = 2)
print("logspace创建的数组：\n",arr_c)

logspace创建的数组：
 [1. 8.]


In [40]:
#特殊矩阵
#单位矩阵:对角线为1，其余元素为0的方阵
arr_eye = numpy.eye(3,4,dtype=int)
print("单位矩阵：\n",arr_eye)

单位矩阵：
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [ ]:
# 对角矩阵：主对角线上元素非零，其余元素为零的方阵
arr_diag = numpy.diag([1,2,3,4])
print("对角矩阵：\n",arr_diag)

对角矩阵：
 [[1 0]
 [0 2]]
