## 1.ndarray的特性
### 多维性

In [1]:
import numpy

In [3]:
arr = numpy.array(3)#零维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

3的维度为： 0


In [4]:
arr = numpy.array([1,2,3])#1维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

[1 2 3]的维度为： 1


In [5]:
arr = numpy.array([[4,5,6],[1,2,3]])#2维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

[[4 5 6]
 [1 2 3]]的维度为： 2


### 同质性

In [6]:
arr = numpy.array([1,"hello"])#不同数据类型会被转换成统一的数据类型
print(f"{arr}的数据类型为：",arr.dtype)

['1' 'hello']的数据类型为： <U11


### 2.ndarray属性

In [7]:
arr = numpy.array(3)
print("数组形状为：",arr.shape)
print("数组维度为：",arr.ndim)
print("元素的个数为：",arr.size) 
print("元素的数据类型：",arr.dtype)

数组形状为： ()
数组维度为： 0
元素的个数为： 1
元素的数据类型： int32


In [8]:
arr_1 = numpy.array([1,2.5,3])
print("数组形状为：",arr_1.shape)
print("数组维度为：",arr_1.ndim)
print("元素的个数为：",arr_1.size)
print("元素的数据类型：",arr_1.dtype)

数组形状为： (3,)
数组维度为： 1
元素的个数为： 3
元素的数据类型： float64


In [9]:
arr_2 = numpy.array([[1,2,3],[4,5,6]])
print("数组形状为：",arr_2.shape)
print("数组维度为：",arr_2.ndim)
print("元素的个数为：",arr_2.size)
print("元素的数据类型：",arr_2.dtype)
print("元素的转置：",arr_2.T)

数组形状为： (2, 3)
数组维度为： 2
元素的个数为： 6
元素的数据类型： int32
元素的转置： [[1 4]
 [2 5]
 [3 6]]


### 3.ndarray的创建

In [10]:
# 预定义形状

arr_zeros = numpy.zeros((2,3),dtype=int)
print("全零二维三列数组：\n",arr_zeros)

全零二维三列数组：
 [[0 0 0]
 [0 0 0]]


In [38]:
# 拼接
arr1 = numpy.array([1, 2, 3])
arr2 = numpy.array([4, 5, 6])
arr_concat = numpy.concatenate((arr1, arr2))
print("拼接后的数组：", arr_concat)

拼接后的数组： [1 2 3 4 5 6]


In [11]:
arr_ones = numpy.ones((2,3))
print("全一二维数组：\n",arr_ones)

全一二维数组：
 [[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
arr_empty = numpy.empty((3,3)) 
print("空二维数组：\n",arr_empty)

空二维数组：
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
arr_pull = numpy.full((2,3),7)
print("全7二维数组：\n",arr_pull)

全7二维数组：
 [[7 7 7]
 [7 7 7]]


In [14]:
# 根据已有数组形状创建新数组
arr_empty_like = numpy.empty_like(arr_pull)
print("根据arr_pull形状创建的空数组：\n",arr_empty_like)
print("--- ----------------------------------------------")
arr_ones_like = numpy.ones_like(arr_pull)
print("根据arr_pull形状创建的全一数组：\n",arr_ones_like)
print("--- ----------------------------------------------")
arr_zeros_like = numpy.zeros_like(arr_pull)
print("根据arr_pull形状创建的全零数组：\n",arr_zeros_like)
print("--- ----------------------------------------------")
arr_full_like = numpy.full_like(arr_pull,9)
print("根据arr_pull形状创建的全9数组：\n",arr_full_like)

根据arr_pull形状创建的空数组：
 [[0 0 0]
 [0 0 0]]
--- ----------------------------------------------
根据arr_pull形状创建的全一数组：
 [[1 1 1]
 [1 1 1]]
--- ----------------------------------------------
根据arr_pull形状创建的全零数组：
 [[0 0 0]
 [0 0 0]]
--- ----------------------------------------------
根据arr_pull形状创建的全9数组：
 [[9 9 9]
 [9 9 9]]


In [15]:
#
arr_a = numpy.arange(1,10,2)
print("arange创建的数组：\n",arr_a)


arange创建的数组：
 [1 3 5 7 9]


In [16]:
#等间隔数列
arr_b = numpy.linspace(0,100,5)
print("linspace创建的数组：\n",arr_b)
print("--- ----------------------------------------------")
arr_b_arange = numpy.arange(0,101,25)
print("arange创建的等间隔数组：\n",arr_b_arange)

linspace创建的数组：
 [  0.  25.  50.  75. 100.]
--- ----------------------------------------------
arange创建的等间隔数组：
 [  0  25  50  75 100]


In [17]:
#对数等差数列
arr_c = numpy.logspace(0,3,2,base = 2)
print("logspace创建的数组：\n",arr_c)

logspace创建的数组：
 [1. 8.]


In [18]:
#特殊矩阵
#单位矩阵:对角线为1，其余元素为0的方阵
arr_eye = numpy.eye(3,4,dtype=int)
print("单位矩阵：\n",arr_eye)

单位矩阵：
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [19]:
# 对角矩阵：主对角线上元素非零，其余元素为零的方阵
arr_diag = numpy.diag([1,2,3,4])
print("对角矩阵：\n",arr_diag)

对角矩阵：
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [20]:
# 随机数矩阵
# 生成0-1之间均匀分布的随机数矩阵
arr_rand = numpy.random.rand(2,3)#二行三列
print("随机数矩阵：\n",arr_rand)

随机数矩阵：
 [[0.35153474 0.77295751 0.9214037 ]
 [0.4522291  0.05327345 0.67942226]]


In [21]:
# 生成指定区间的随机浮点数
arr_uniform = numpy.random.uniform(1,10,(2,3))#1-10 二行三列
print("均匀分布随机数矩阵：\n",arr_uniform)

均匀分布随机数矩阵：
 [[6.40897202 3.21573318 2.70968539]
 [7.67979479 3.03942669 3.86254881]]


In [22]:
# 生成指定区间的随机整数
arr_randint = numpy.random.randint(1,10,(2,3))#1-10 二行三列
print("随机整数矩阵：\n",arr_randint)

随机整数矩阵：
 [[7 9 8]
 [5 9 9]]


In [23]:
# 生成随机数（正态分布）-3 -  3
arr_randn = numpy.random.randn(2,3) #二行三列
print("正态分布随机数矩阵：\n",arr_randn)

正态分布随机数矩阵：
 [[-1.8688762  -1.61395835  1.55359412]
 [ 0.58767901  1.0107779   0.16411267]]


In [24]:
# 生成随机种子
numpy.random.seed(20)
arr_randint = numpy.random.randint(1,10,(2,3))#1-10 二行三列
print("设置随机种子后的随机整数矩阵：\n",arr_randint)

设置随机种子后的随机整数矩阵：
 [[4 5 7]
 [8 3 1]]


### 4,ndarray的数据类型
##### 布尔类型：bool
##### 整数类型：int
##### 浮点数类型：float
##### 复数类型：complex


In [25]:
# 映射为对应类型 注意范围
arr = numpy.array([1,0,1,0,0], dtype=bool)
print(f"{arr}的数据类型为：",arr.dtype)

[ True False  True False False]的数据类型为： bool


### 5.索引与切片

In [26]:
arr = numpy.random.randint(1,100,30)
print("随机生成的整数数组为：\n",arr)

随机生成的整数数组为：
 [41 86 91 27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95
 33 11  7 76 19  4]


In [27]:
# 对一维数组进行切片 支持逻辑运算符
print(arr[:])#获取全部元素
print("-- ----------------------------------------------")
print(arr[slice(2,20,1)])
print("--- ----------------------------------------------")
print(arr[0:5])#从索引0到5(不包含5)步长默认为1
print("--- ----------------------------------------------")
print(arr[0:10:2])#从索引0到10(不包含10)步长为2
print("--- ----------------------------------------------")
print(arr[arr>10])#大于10的元素

[41 86 91 27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95
 33 11  7 76 19  4]
-- ----------------------------------------------
[91 27 84 17 63 17  8 99  7 27 14 76 59 26  4 75 76 62]
--- ----------------------------------------------
[41 86 91 27 84]
--- ----------------------------------------------
[41 91 84 63  8]
--- ----------------------------------------------
[41 86 91 27 84 17 63 17 99 27 14 76 59 26 75 76 62 78 84 58 95 33 11 76
 19]


In [28]:
arr = numpy.random.randint(1,100,(3,4))
print("随机生成的二维整数数组为：\n",arr)

随机生成的二维整数数组为：
 [[78 18 44 17]
 [19 80 91 60]
 [72 76 30 46]]


In [29]:
print(arr[1,2])#获取第2行第3列元素
print("--- ----------------------------------------------")
print(arr[:,:])#获取所有行所有列元素
print("--- ----------------------------------------------")
print(arr[0:3,2:4])#获取第1到3行，第3到4列元素
print("--- ----------------------------------------------")
print(arr[2][arr[2] > 50])#获取第3行大于50的元素
print("--- ----------------------------------------------")

91
--- ----------------------------------------------
[[78 18 44 17]
 [19 80 91 60]
 [72 76 30 46]]
--- ----------------------------------------------
[[44 17]
 [91 60]
 [30 46]]
--- ----------------------------------------------
[72 76]
--- ----------------------------------------------


### 6.ndarray的运算

In [30]:
arr_a = numpy.array([1,2,3,4])
arr_b = numpy.array([5,6,7,8])
print(arr_a + arr_b)
print(arr_a - arr_b)
print(arr_a * arr_b)
print(arr_b / arr_a)
print(arr_a // arr_b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]
[0 0 0 0]


In [31]:
# 广播机制 
arr_a = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
arr_b = numpy.array([1,0,1])
print("arr_a + arr_b的结果为：\n",arr_a + arr_b)

arr_a + arr_b的结果为：
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [32]:
# 矩阵运算 1*7+2*9+3*11=58
arr_a = numpy.array([[1,2,3],[4,5,6]])
arr_b = numpy.array([[7,8,9],[9,10,11],[11,12,13]])
print("矩阵乘法结果为：\n",arr_a@arr_b)

矩阵乘法结果为：
 [[ 58  64  70]
 [139 154 169]]


### 2.3ndarray常用数学函数
#### 1.基本数学函数

In [33]:
#计算平方根 返回的结果是浮点数
print(numpy.sqrt(9))
print("--- ----------------------------------------------")
print(numpy.sqrt([9,16,25]))

3.0
--- ----------------------------------------------
[3. 4. 5.]


In [36]:
# 计算平方
print(numpy.square(3))
print("--- ----------------------------------------------")
# 计算对数
print(numpy.log(10))
print("--- ----------------------------------------------")
#计算指数
print(numpy.exp(3))

9
--- ----------------------------------------------
2.302585092994046
--- ----------------------------------------------
20.085536923187668


In [37]:
#计算正弦值
arr = numpy.array([0,30,90])
print(numpy.sin(arr*numpy.pi/180))
#计算余弦值
print(numpy.cos(arr*numpy.pi/180))
#计算正切值
print(numpy.tan(arr*numpy.pi/180))


[0.  0.5 1. ]
[1.00000000e+00 8.66025404e-01 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.63312394e+16]
